Repository wecode-bootcamp-korea/48-2nd-F_Kiiler-frontend, pull requests merged in 2023-08, with the labels that each got.

#1 공통 컴포넌트(HeaderTop, HeaderMain) 폰트 수정
  package-lock.json
  package.json
  src/components/HeaderMain/HeaderMain.js
  src/components/HeaderMain/HeaderMain.scss
  src/components/HeaderTop/HeaderTop.js
  src/components/HeaderTop/HeaderTop.scss
  src/pages/SignUp/SignUp.js
  src/styles/common.scss
Labels: 완료

#3 style : 공통 폰트 변경
  public/index.html
  src/styles/common.scss
Labels: 멘토 리뷰 요청

#5 브랜치 이름 수정/headerMain, InputBox 컴포넌트 수정
  src/API/login.js
  src/Router.js
  src/components/HeaderMain/HeaderMain.js
  src/components/HeaderMain/HeaderMain.scss
  src/components/HeaderTop/HeaderTop.js
  src/components/InputBox/InputBox.jsx
  src/components/InputBox/InputBox.scss
  src/components/LoginSignUpButton/LoginSignUpButton.jsx
  src/components/LoginSignUpButton/LoginSignUpButton.scss
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: 완료

#10 로그인 상태 관리 관리 구현 / 로그인 fetch함수 수정
  src/API/login.js
  src/components/Footer/Footer.js
  src/components/HeaderTop/HeaderTop.js
  src/pages/Login/Login.js
Labels: 멘토 리뷰 요청, 완료

#8 Add : 사이즈 선택 ui, moakData, SelectButton 컴포넌트, ProductInfo 컴포넌트 분리
  public/data/data.json
  public/data/productData.json
  public/data/sizeSelectData.json
  public/images/shoe1.jpg
  public/images/thunder.png
  src/components/ProductInfo/ProductInfo.js
  src/components/ProductInfo/ProductInfo.scss
  src/components/SelectItem/SelectItem.js
  src/components/SelectItem/SelectItem.scss
  src/pages/SizeSelect/SizeSelect.js
  src/pages/SizeSelect/SizeSelect.scss
Labels: 수정 요청

#9 Add : 즉시 구매, 구매 입찰 ui 완성
  src/components/BidDeadline/BidDeadline.js
  src/components/BidDeadline/BidDeadline.scss
  src/pages/TradeOption/TradeOption.js
  src/pages/TradeOption/TradeOption.scss
Labels: 멘토 리뷰 요청

#11 Add : 결제 페이지 ui 완성
  public/images/express.png
  public/images/noexpress.png
  src/components/HeaderMain/HeaderMain.scss
  src/pages/Payment/Payment.js
  src/pages/Payment/Payment.scss
Labels: 멘토 리뷰 요청

#7 상품 리스트 컴포넌트 (merge 부탁드립니다)
  public/data/data.json
  public/images/expressThunder.PNG
  public/images/sampleImg.PNG
  public/images/shoes.PNG
  public/images/trendViewport.PNG
  src/API/fetchProductList.js
  src/components/HeaderMain/HeaderMain.js
  src/components/HeaderMain/HeaderMain.scss
  src/components/HeaderTop/HeaderTop.scss
  src/pages/Login/Login.scss
  src/pages/ProductDetail/DetialRightTop/DetailRightTop.js
  src/pages/ProductList/FilteringCategory/FilteringCategory.js
  src/pages/ProductList/FilteringCategory/FilteringCategory.scss
  src/pages/ProductList/ProductCard/ProductCard.js
  src/pages/ProductList/ProductCard/ProductCard.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/ProductList/SearchResultList/SearchResultList.js
  src/pages/ProductList/SearchResultList/SearchResultList.scss
  src/pages/ProductList/SortingResult/SortingResult.js
  src/pages/ProductList/SortingResult/SortingResult.scss
Labels: 완료

#12 상품 디테일 페이지 기능구현 완료
  public/data/askTableData.json
  public/data/bidTableData.json
  public/data/detailData.json
  public/images/samba.PNG
  src/API/getBuyBidsHistory.js
  src/API/getProductDetail.js
  src/API/getProductList.js
  src/API/getSellBidsHistory.js
  src/API/login.js
  src/API/postLogin.js
  src/API/postSignUp.js
  src/Router.js
  src/components/HeaderMain/HeaderMain.scss
  src/components/HeaderTop/HeaderTop.js
  src/components/ProductInfo/ProductInfo.scss
  src/components/SizeSelectModal/SizeSelectModal.jsx
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/ProductDetail/DataTable/DataTable.js
  src/pages/ProductDetail/DataTable/DataTable.scss
  src/pages/ProductDetail/DetailLeftBox/DetailLeftBox.js
  src/pages/ProductDetail/DetailLeftBox/DetailLeftBox.scss
  src/pages/ProductDetail/DetailRightBox/DetailRightBox.js
  src/pages/ProductDetail/DetailRightBox/DetailRightBox.scss
  src/pages/ProductDetail/DetialRightTop/DetailRightTop.js
  src/pages/ProductDetail/DetialRightTop/DetailRightTop.scss
  src/pages/ProductDetail/ProductBids/ProductBids.js
  src/pages/ProductDetail/ProductBids/ProductBids.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/ProductInfo/ProductInfo.js
  src/pages/ProductDetail/ProductInfo/ProductInfo.scss
  src/pages/ProductList/ProductCard/ProductCard.js
  src/pages/ProductList/ProductCard/ProductCard.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/SearchResultList/SearchResultList.js
  src/pages/ProductList/SearchResultList/SearchResultList.scss
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
  src/pages/SignUp/SizeSelectModal/SizeSelectModal.jsx
  src/pages/SignUp/SizeSelectModal/SizeSelectModal.scss
Labels: 완료

#13 Modify : payment API까지 수정
  public/data/productData.json
  public/data/sizeSelectData.json
  src/API/postLogin.js
  src/API/postSignUp.js
  src/Router.js
  src/components/BidDeadline/BidDeadline.js
  src/components/BidDeadline/BidDeadline.scss
  src/components/ProductInfo/ProductInfo.js
  src/components/ProductInfo/ProductInfo.scss
  src/components/SelectItem/SelectItem.js
  src/components/SelectItem/SelectItem.scss
  src/pages/Login/Login.js
  src/pages/Payment/ModalPayment/ModalPayment.js
  src/pages/Payment/ModalPayment/ModalPayment.scss
  src/pages/Payment/Payment.js
  src/pages/Payment/Payment.scss
  src/pages/ProductDetail/DetailRightBox/DetailRightBox.js
  src/pages/ProductDetail/DetialRightTop/DetailRightTop.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/PurchaseOption/PurchaseOption.js
  src/pages/PurchaseOption/PurchaseOption.scss
  src/pages/SellOption/SellOption.js
  src/pages/SellOption/SellOption.scss
  src/pages/SizeSelect/SizeSelect.js
  src/pages/SizeSelect/SizeSelect.scss
  src/pages/TradeOption/TradeOption.scss
Labels: 멘토 리뷰 요청
